In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Import Necessary Libraries

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Explore Dataset

In [11]:
df = pd.read_csv('../input/maritime-disasters-of-the-20th-century/Maritime disasters of the 20th century.csv')

In [12]:
df

# Data Preprocessing

In [13]:
df = df.drop(['Unnamed: 0'], axis = 1)

In [15]:
# Create a New Interval Column
df['Interval'] = (10 * (df['The year of the disaster'] // 10)).astype(str) + 's'

In [16]:
df.dtypes

In [17]:
df.head(5)

In [18]:
# Plot to see null values in our data
sns.heatmap(df.isnull(), cbar=False)

In [19]:
# Null Value Percentage Per column
percent_missing = df.isnull().sum() * 100 / len(df)
missing_value_df = pd.DataFrame({'column_name': df.columns,
                                 'percent_missing': percent_missing})
missing_value_df

# EDA

In [20]:
# plot correlation matrix of numeric variables
f = plt.figure(figsize=(8,5))
plt.matshow(df.corr(), fignum=f.number)
plt.xticks(range(df.select_dtypes(['number']).shape[1]), df.select_dtypes(['number']).columns, fontsize=14, rotation=45)
plt.yticks(range(df.select_dtypes(['number']).shape[1]), df.select_dtypes(['number']).columns, fontsize=14)
cb = plt.colorbar()
cb.ax.tick_params(labelsize=14)

In [21]:
data = df
cad = data[['The country ship belongs to','Number of deaths']].groupby(['The country ship belongs to']).sum().reset_index().sort_values('Number of deaths', ascending = False)

In [22]:
cad.head(5)

In [23]:
plt.figure(figsize = (15,15))
sns.barplot(y = 'The country ship belongs to', x = 'Number of deaths', data = cad, palette = 'mako')
plt.xlabel('Total Number of deaths', size = 15, color='midnightblue')
plt.ylabel('')
plt.xticks(color='midnightblue')
plt.yticks(color='midnightblue')
plt.title('Total Number of deaths with respect to Countries', size = 15, color='midnightblue')

In [24]:
df.head(5)

In [27]:
data = df
IAD = data[['Interval','Number of deaths']].groupby(['Interval']).sum().reset_index().sort_values('Number of deaths', ascending = False)

In [28]:
IAD

In [33]:
plt.figure(figsize = (18,15))
sns.barplot(y = 'Number of deaths', x = 'Interval', data = IAD, palette = 'magma')
plt.xlabel('Respective Decade', size = 15, color='midnightblue')
plt.ylabel('Total Number of deaths', size = 15, color='midnightblue')
plt.xticks(color='midnightblue')
plt.yticks(color='midnightblue')
plt.title('Total Number of deaths in respective Decade', size = 15, color='midnightblue')

In [34]:
for elem in df['The name of the ship'].unique():
    print(elem)

In [35]:
data = df
SAD = data[['The name of the ship','Number of deaths']].groupby(['The name of the ship']).sum().reset_index().sort_values('Number of deaths', ascending = False)

In [36]:
SAD.head(5)

In [42]:
plt.figure(figsize = (15,15))
sns.barplot(y = 'The name of the ship', x = 'Number of deaths', data = SAD.nlargest(30, 'Number of deaths'), palette = 'magma')
plt.xlabel('Total Number of deaths', size = 15, color='midnightblue')
plt.ylabel('The name of the Ship', size = 15, color='midnightblue')
plt.xticks(color='midnightblue')
plt.yticks(color='midnightblue')
plt.title('Total Number of deaths against Top 30 Ships', size = 15, color='midnightblue')